# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Magic' do

pod 'AFNetworking'
pod 'Haneke'
use_frameworks!

pod 'AlgoliaSearch-Client-Swift'
pod 'SwiftyJSON'

end

